import { index, primaryKey, sqliteTable, text } from "drizzle-orm/sqlite-core";

/**
 * What D1 holds.
 *
 * Not much, and that is the design. A group's ledger — members, entries,
 * payers, shares, events, invites — lives in that group's Durable Object,
 * which is the only thing that may write it. D1 holds the four things that are
 * genuinely cross-group and cannot live inside any one of them, plus Better
 * Auth's own tables, which are generated into `src/auth-schema.ts`.
 *
 * Timestamps are ISO-8601 strings rather than integers. They cross the wire as
 * strings, they are compared as strings by the profile feed's cursor, and
 * lexical order is chronological order for this format — so storing them any
 * other way would mean converting at every boundary to buy nothing.
 */

/**
 * A person, as the app displays them.
 *
 * Separate from Better Auth's `user` on purpose. That table is regenerated by
 * `auth generate` on every upgrade, and the ledger's idea of who somebody is
 * should not sit inside something a dependency bump rewrites.
 *
 * One row per account, created by a databaseHook when the account is.
 */
export const profiles = sqliteTable(
  "profiles",
  {
    id: text("id").primaryKey(),

    /**
     * Null until somebody chooses one, and the null is load-bearing rather
     * than lazy. Claiming an invite adopts the name a friend typed on the
     * placeholder only when the profile has none of its own; a sentinel like
     * 'Someone' could not tell a name nobody chose from a name somebody meant.
     */
    displayName: text("display_name"),

    /**
     * The payment handle a settle-up hands off to. The one column in this
     * schema that can redirect real money, which is why nothing but its owner
     * may write it — see the member rules in the Durable Object.
     */
    upiVpa: text("upi_vpa"),

    /** Cursored by the client's profile feed, so a rename travels. */
    updatedAt: text("updated_at").notNull(),

    /**
     * Set by account deletion. The row survives so co-members' history still
     * resolves a name, while the account behind it is gone.
     */
    deletedAt: text("deleted_at"),
  },
  (table) => [index("profiles_updated").on(table.updatedAt, table.id)],
);

/**
 * Which groups a person is in.
 *
 * A derived index, not the truth. Each group's Durable Object owns its member
 * list and writes here afterwards; this exists so "my groups" does not mean
 * asking every Durable Object, and so a request can be refused cheaply before
 * a stub is created.
 *
 * It is allowed to be briefly stale in exactly one direction. A first-pass
 * check that says "no" where the Durable Object would say "yes" costs a retry.
 * The Durable Object re-checks membership itself and is the authority, so a
 * stale row here can never grant access it should not.
 */
export const memberships = sqliteTable(
  "memberships",
  {
    profileId: text("profile_id").notNull(),
    groupId: text("group_id").notNull(),

    /**
     * Leaving is a column, not a deletion: the client has to learn that
     * somebody left, and a row that vanishes tells nobody anything.
     */
    leftAt: text("left_at"),
    updatedAt: text("updated_at").notNull(),
  },
  (table) => [
    // One row per person per group, enforced rather than assumed: two rows
    // would be two balances for the same human that can never be reconciled.
    primaryKey({ columns: [table.profileId, table.groupId] }),
    index("memberships_group").on(table.groupId),
  ],
);

/**
 * Where to wake somebody.
 *
 * Read by a group's Durable Object when it has committed something worth a
 * notification: it knows its members' profile ids, and this turns those into
 * devices.
 */
export const deviceTokens = sqliteTable(
  "device_tokens",
  {
    token: text("token").primaryKey(),
    profileId: text("profile_id").notNull(),
    platform: text("platform", { enum: ["android", "web"] }).notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (table) => [index("device_tokens_profile").on(table.profileId)],
);

/**
 * Which group a link is for.
 *
 * Redemption happens before membership — that is the whole point of an invite
 * — so somebody holding a token has to be routed to a group they cannot yet
 * read. This is the smallest thing that can do that: a token, and the group
 * whose Durable Object knows what the token actually means.
 *
 * Deliberately carries no state about whether the link is spent, expired or
 * revoked. That lives in the Durable Object, which is the only thing that can
 * answer it without a race.
 */
export const linkTokens = sqliteTable(
  "link_tokens",
  {
    token: text("token").primaryKey(),
    groupId: text("group_id").notNull(),

    /**
     * 'invite' hands one named placeholder to one person. 'group_link' lets
     * anybody holding it walk in, any number of times, until it expires or is
     * revoked. The URL is identical for both; which kind a token is is the
     * server's business, not the URL's.
     */
    kind: text("kind", { enum: ["invite", "group_link"] }).notNull(),
    createdAt: text("created_at").notNull(),
  },
  (table) => [index("link_tokens_group").on(table.groupId)],
);
